### ISSUE TITLE
A large part of events & decisions from BAI are still not installed yet?

### ISSUE THREAD

**Issue by stcarl-order** [TurningPointNovocherkassk/Historical_Bloat_Mod#10]
Although many contents can be seen in 00_BAI_decisions.csv & 00_BAI_events.csv, I can't find those in the events &  decisions folder.

**Comment by TurningPointNovocherkassk** [comment]
Yes, figured out it would be easier to simply copy the whole file rather than localizing all events and decisions one by one. There's a lot of leftover stuff I'm not really planning to add, just ignore those.

**Comment by stcarl-order** [comment]
I see.Thanks!
