### ISSUE TITLE
Armies of annexed countries

### ISSUE THREAD

**Issue by Karlings** [TurningPointNovocherkassk/Historical_Bloat_Mod#11]
![Screenshot (628)](https://user-images.githubusercontent.com/88304695/127807131-ee7df401-d779-4542-b02f-92ddf1d8c68d.png)

For some reason they didn't disappear after the Unification of Germany, maybe because they were attacking Austria and France?

**Comment by TurningPointNovocherkassk** [comment]
For how long have these ghost armies existed? They're usually annexed once the AI/player takes a cleanup decision, might take a few months for the AI.

**Comment by Karlings** [comment]
For a year and a half, but it was fixed after I load and wait for the AI to get home. I also just noticed that italy is having the same problem for like 10 or 11 years with those fleets

![Screenshot (629)](https://user-images.githubusercontent.com/88304695/127944784-4d9c169f-1597-4e0b-8d23-0c762b9f8040.png)

**Comment by TurningPointNovocherkassk** [comment]
Yeah that's kind of a vanilla AI issue. The cleanup decision/event chain from vanilla HFM/HPM isn't 100% reliable either, but it's something at least.
If it gets too annoying (or the stuff isn't cleaned upon reloading a save), I'd suggest manually giving a single province to the ghost country via console and waiting until all fleets are harbored, then give it back to the previous country (Italy in this case.)

**Comment by Karlings** [comment]
Never thought about that, I'm not the console type but that's very ingenious


It's not serious at all btw, I just found it sort of out of place haha

Thanks man and great mod.
