### ISSUE TITLE
Mexico Decision of Establish the Rancho System Cause Game Crush

### ISSUE THREAD

**Issue by KingofIronCap** [TurningPointNovocherkassk/Historical_Bloat_Mod#12]
When player nation is Mexico, the decision “establish the rancho system” would cause the game freeze for a glimpse and crush. Even stop the cursor on the question mark button to check decision prerequisites or on the execute decision button would cause the same problem. 
For AI Mexico, the AI is able to take the decision and not causing any issues, but I’m still unsure the effects, is it supposed to give any buff to the northern Mexican provinces or change the local population constitute?

**Comment by TurningPointNovocherkassk** [comment]
Thank you, it's been fixed and uploaded.
