### ISSUE TITLE
Infinite prestige

### ISSUE THREAD

**Issue by Karlings** [TurningPointNovocherkassk/Historical_Bloat_Mod#14]
![Screenshot (630)](https://user-images.githubusercontent.com/88304695/128257354-54befc5b-1de3-4963-812a-d75e0a735af9.png)

The decisions "Conquest of the Desert" and "Occupation of Araucania" appears to be in an infinite loop making Argentina (AI) the prestigious country in the world in less than a year

**Comment by Karlings** [comment]
Something similar happened in brazil, but it was just one time around the same date

**Comment by TurningPointNovocherkassk** [comment]
Fixed and uploaded, thank you for your contribution.

>Something similar happened in brazil, but it was just one time around the same date

If you got a game log from that date, please do post or upload somewhere like pastebin. They're located in \Documents\Paradox Interactive\Victoria II\HFM\logs; I specifically need game.log.

**Comment by Karlings** [comment]
Unfortunately I don't have it, but I will report it instantly if I found it again in my next playthrough
