### ISSUE TITLE
Suez canal bug

### ISSUE THREAD

**Issue by darkmatter1944** [TurningPointNovocherkassk/Historical_Bloat_Mod#2]
When playing as usually Ottomans or Italy event 36971 never triggers after building suez canal modifier ends. Have to trigger it manually, and event has same title and picture as "panama canal company" event. Global flag "suez_canal_built" doesn't seem to fire right.

Also wtf happened to the discord did I get banned today or did it disappear

**Comment by TurningPointNovocherkassk** [comment]
Can't pm you because we don't share servers.
