### ISSUE TITLE
Why always FSA？

### ISSUE THREAD

**Issue by stcarl-order** [TurningPointNovocherkassk/Historical_Bloat_Mod#4]
I've played at least 7 games，but it confuses me why ACW is always the non-historical route.Each time AI USA released FSA instead of historical CSA.I really doubt it is just coincidence, not bug?

**Comment by TurningPointNovocherkassk** [comment]
Honestly I've never seen this happen myself nor in all the player saves (from the latest commit) I've checked. I'll keep an eye out for this though, thanks.

**Comment by stcarl-order** [comment]
Report a newly-discovered bug.the desicion central_ukraine_mineral_basin can be repeatedly executed, because its effect is wrong.It should be central_ukraine_modifier,but mistakenly written as donbass_modifier.

**Comment by TurningPointNovocherkassk** [comment]
Solved. Thank you.
