### ISSUE TITLE
Question about French language schooling

### ISSUE THREAD

**Issue by Sleep206** [TurningPointNovocherkassk/Historical_Bloat_Mod#5]
Excuse me, sir,  I found that ‘french language schooling’ decision in your mod can only remove Arpitan (new country) core while you added bunch of cores for french acceptable pops so we can't assimilative them after clicking this decision. Is that mean you dont suggested to click this decision or what? Could you please tell me your suggestion about this decision?

Also, I found ‘remove catalan as acceptable culture’ in this decision but I can't find any decision or event that France accept catalan. It's useless for now or you have other plan ?

Last, I wonder if  French can make Mexico as a vassal by taking badboy after their successful intervention. What's your opnion, Sir? Could you please add this decision or event if you think is reasonable and acceptable?

Thank you!

**Comment by TurningPointNovocherkassk** [comment]
> I found that ‘french language schooling’ decision in your mod can only remove Arpitan (new country) core while you added bunch of cores for french acceptable pops so we can't assimilative them after clicking this decision. Is that mean you dont suggested to click this decision or what? Could you please tell me your suggestion about this decision?
This is an old HFM decision I forgot to update, it should now properly remove all cores from those french regional cultures. Honestly I've never played France, so whether the decision is good or not it's up to the player. I suppose if you're playing a nationalist you'd want all those regional cultures assimilated to the dominant french culture.

> Also, I found ‘remove catalan as acceptable culture’ in this decision but I can't find any decision or event that France accept catalan. It's useless for now or you have other plan ?
You can claim Catalonia as France upon taking the pan french nationalism decision. Gotta be the 2nd French Empire though.

> Last, I wonder if French can make Mexico as a vassal by taking badboy after their successful intervention. What's your opnion, Sir? Could you please add this decision or event if you think is reasonable and acceptable?
You make a Mexican Empire vassal as France if Mexico's ruled by liberals and France (or Bourbon France) gave them a loan and didn't get their money back from Mexico. An event will be triggered in which France can choose to start the second Mexican intervention along with whatever other European Countries had loaned them money; stay long enough and you can place Maximilian I on the throne.

**Comment by Sleep206** [comment]
First, sir thanks for your answer. For the second question, what I want to ask is how to accept catalan as accpeted culture in your mod because catalonia is the only one region that bring France a bunch of non-accpeted pops while other conquered region are accpeted culture or can be assimilative in some condition.

On the other hand, I found that I can't use CB 'acquire Substate region' (can't use to declear war or add it during war) against united kingdom after this update, maybe u can check it out when you are free?

Finally, thanks for your continuous update, sir, its a good and realistic mod.
