### ISSUE TITLE
TEXAS Repeatly Ennact the "Rename Texas" Decision

### ISSUE THREAD

**Issue by KingofIronCap** [TurningPointNovocherkassk/Historical_Bloat_Mod#8]
It seems like the same problem as the old Cornwall rename of Britain and Slovakia rename of KUK. Though not as serious to the overall gameplay as TEX has a low chance of becoming a Great Power, but would be nice if it can be fixed!

**Comment by KingofIronCap** [comment]
Not sure if the same thing occurs on other TEX cores such as Nuevo Mexico, Tejas del Oeste and parts of Oklahoma and Kansas.

**Comment by TurningPointNovocherkassk** [comment]
Thanks, a fix will be provided in the next bugfix commit.
