### ISSUE TITLE
Problem about USA minor event "Secssionist Setiments" to increase soldier pop & give CSA core

### ISSUE THREAD

**Issue by KingofIronCap** [TurningPointNovocherkassk/Historical_Bloat_Mod#9]
Seems like the event is supposed to only pop once or only occur in a specific province per time fired. It grants CSA core and increases soldier pop by 50%, I think in the 1850s it fires every few days as far as I observed when tagged to the USA. After a few years, about half of the USA's population will be turned into soldiers and with many provinces that gained after the US-Mexico War having 100% of its pop as soldiers. These provinces usually rebel and for most of the time, and the USA (ai) is unable to suppress the rebel and cause overthrown of the state.
For example, in one of my savegames, in the year 1856, the USA has a total of 55.37M pop and 13.84M in the workforce with 44% of them are soldiers.
![EV3H0X59 PG(TKG% 7HPY6U](https://user-images.githubusercontent.com/87465485/126904829-dc233de2-96aa-4840-908e-1f32bcbbfbad.png)

**Comment by TurningPointNovocherkassk** [comment]
Is this from the latest commit?

**Comment by KingofIronCap** [comment]
> Is this from the latest commit?

The screenshot is from the older version, I just tried on the newest update and so far as I observed the same problem no longer occur. Thanks for notice!

**Comment by TurningPointNovocherkassk** [comment]
No problem, thanks for your input.
